# Generated by Django 4.1.1 on 2022-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.IntegerField()),
                ('className', models.CharField(max_length=200)),
            ],
        ),
    ]
