# Generated by Django 4.1.1 on 2022-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_standard_delete_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='stdID',
            field=models.CharField(max_length=200),
        ),
    ]
