# Generated by Django 4.1.1 on 2022-09-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0003_alter_standard_stdid'),
        ('student_class_maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Class_Map',
            new_name='StudentClassMap',
        ),
    ]
