# Generated by Django 4.1.1 on 2022-09-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_class_maps', '0002_rename_student_class_map_studentclassmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassmap',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentclassmap',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
